name: Build Docker Container

on:
  push:
    branches:
      - main
      - master 

jobs:
  docker-build-web:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (web)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/web"
          push: true
          tags: innerspeech/web:latest, innerspeech/web:${{ github.sha }}
  docker-build-tts:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (tts)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/tts"
          push: true
          tags: innerspeech/tts:latest, innerspeech/tts:${{ github.sha }}
  docker-build-asr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (asr)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/asr"
          push: true
          tags: innerspeech/asr:latest, innerspeech/asr:${{ github.sha }}
  docker-build-llm:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (llm)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/llm"
          push: true
          tags: innerspeech/llm:latest, innerspeech/llm:${{ github.sha }}
  docker-build-nemo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (nemo)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/nemo"
          push: true
          tags: innerspeech/nemo:latest, innerspeech/nemo:${{ github.sha }}
  docker-build-bci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (nemo)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/bci"
          push: true
          tags: innerspeech/bci:latest, innerspeech/bci:${{ github.sha }}