name: Build Docker Container

on:
  push:
    branches:
      - main
      - master 

jobs:
  docker-build-web:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (web)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/web"
          push: true
          tags: innerspeech/web:latest
  docker-build-tts:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (tts)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/tts"
          push: true
          tags: innerspeech/tts:latest
  docker-build-asr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (asr)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/asr"
          push: true
          tags: innerspeech/asr:latest
  docker-build-llm:
    runs-on: ubuntu-latest
    steps:
      - name: Variables set up
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
      - name: Show env
        run: |
          echo "Branch: ${{ env.branch }}"
          echo "Sha: ${{ env.sha_short }}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (llm)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/llm"
          push: true
          tags: innerspeech/llm:"${{ env.branch }}.${{ env.sha_short }}"