name: Build Docker Container

on:
  push:
    branches:
      - main
      - master 

jobs:
  docker-build-web:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (web)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/web"
          push: true
          tags: innerspeech/web:latest
  docker-build-tts:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (tts)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/tts"
          push: true
          tags: innerspeech/tts:latest
  docker-build-asr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (asr)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/asr"
          push: true
          tags: innerspeech/asr:latest
docker-build-llm:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Build and push (llm)
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dockers/llm"
          push: true
          tags: innerspeech/llm:latest